src/Entity/Grade.php
<?php

namespace App\Entity;

use App\Repository\GradeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GradeRepository::class)]
class Grade
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $value = null;

    #[ORM\ManyToOne(inversedBy: 'grade')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Subject $subject = null;

    #[ORM\ManyToOne(inversedBy: 'grade')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Student $student_rating = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getValue(): ?float
    {
        return $this->value;
    }

    public function setValue(float $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getSubject(): ?Subject
    {
        return $this->subject;
    }

    public function setSubject(?Subject $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getStudentRating(): ?Student
    {
        return $this->student_rating;
    }

    public function setStudentRating(?Student $student_rating): self
    {
        $this->student_rating = $student_rating;

        return $this;
    }

    public function __toString()
    {
        return $this->subject . ' ' . $this->student_rating;
    }
}

src/Entity/Student.php
<?php

namespace App\Entity;

use App\Entity\Gender;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\StudentRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: StudentRepository::class)]
class Student
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $gender;

    #[ORM\ManyToMany(targetEntity: Subject::class)]
    private Collection $subject;

    #[ORM\ManyToOne(inversedBy: 'class_students')]
    #[ORM\JoinColumn(nullable: false)]
    private ?SchoolClass $schoolClass = null;

    #[ORM\OneToMany(mappedBy: 'student_rating', targetEntity: Grade::class, orphanRemoval: true)]
    private Collection $grade;

    #[ORM\OneToMany(mappedBy: 'student_appreciation', targetEntity: Subject::class)]
    private Collection $subject_appreciation;



    public function __construct()
    {
        $this->subject = new ArrayCollection();
        $this->grade = new ArrayCollection();
        $this->subject_appreciation = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * @return Collection<int, Subject>
     */
    public function getSubject(): Collection
    {
        return $this->subject;
    }

    public function addSubject(Subject $subject): self
    {
        if (!$this->subject->contains($subject)) {
            $this->subject->add($subject);
        }

        return $this;
    }

    public function removeSubject(Subject $subject): self
    {
        $this->subject->removeElement($subject);

        return $this;
    }

    public function getSchoolClass(): ?SchoolClass
    {
        return $this->schoolClass;
    }

    public function setSchoolClass(?SchoolClass $schoolClass): self
    {
        $this->schoolClass = $schoolClass;

        return $this;
    }


    /**
     * @return Collection<int, Grade>
     */
    public function getGrade(): Collection
    {
        return $this->grade;
    }

    public function addGrade(Grade $grade): self
    {
        if (!$this->grade->contains($grade)) {
            $this->grade->add($grade);
            $grade->setStudentRating($this);
        }

        return $this;
    }

    public function removeGrade(Grade $grade): self
    {
        if ($this->grade->removeElement($grade)) {
            // set the owning side to null (unless already changed)
            if ($grade->getStudentRating() === $this) {
                $grade->setStudentRating(null);
            }
        }

        return $this;
    }




    public function __toString()
    {
        return $this->schoolClass . ' ' . $this->grade . ' ' . $this->subject . ' ';
    }

    /**
     * @return Collection<int, Subject>
     */
    public function getSubjectAppreciation(): Collection
    {
        return $this->subject_appreciation;
    }

    public function addSubjectAppreciation(Subject $subjectAppreciation): self
    {
        if (!$this->subject_appreciation->contains($subjectAppreciation)) {
            $this->subject_appreciation->add($subjectAppreciation);
            $subjectAppreciation->setStudentAppreciation($this);
        }

        return $this;
    }

    public function removeSubjectAppreciation(Subject $subjectAppreciation): self
    {
        if ($this->subject_appreciation->removeElement($subjectAppreciation)) {
            // set the owning side to null (unless already changed)
            if ($subjectAppreciation->getStudentAppreciation() === $this) {
                $subjectAppreciation->setStudentAppreciation(null);
            }
        }

        return $this;
    }
}

src/Entity/Subject.php
<?php

namespace App\Entity;

use App\Repository\SubjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubjectRepository::class)]
class Subject
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $subject_name = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Teacher $subject_teacher = null;

    #[ORM\OneToMany(mappedBy: 'subject', targetEntity: Grade::class, orphanRemoval: true)]
    private Collection $grade;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $appreciation = null;

    #[ORM\ManyToOne(inversedBy: 'subject_appreciation')]
    private ?Student $student_appreciation = null;




    public function __construct()
    {
        $this->grade = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSubjectName(): ?string
    {
        return $this->subject_name;
    }

    public function setSubjectName(string $subject_name): self
    {
        $this->subject_name = $subject_name;

        return $this;
    }

    public function getSubjectTeacher(): ?Teacher
    {
        return $this->subject_teacher;
    }

    public function setSubjectTeacher(Teacher $subject_teacher): self
    {
        $this->subject_teacher = $subject_teacher;

        return $this;
    }

    /**
     * @return Collection<int, Grade>
     */
    public function getGrade(): Collection
    {
        return $this->grade;
    }

    public function addGrade(Grade $grade): self
    {
        if (!$this->grade->contains($grade)) {
            $this->grade->add($grade);
            $grade->setSubject($this);
        }

        return $this;
    }

    public function removeGrade(Grade $grade): self
    {
        if ($this->grade->removeElement($grade)) {
            // set the owning side to null (unless already changed)
            if ($grade->getSubject() === $this) {
                $grade->setSubject(null);
            }
        }

        return $this;
    }

    public function getAppreciation(): ?string
    {
        return $this->appreciation;
    }

    public function setAppreciation(?string $appreciation): self
    {
        $this->appreciation = $appreciation;

        return $this;
    }

    public function getStudentAppreciation(): ?Student
    {
        return $this->student_appreciation;
    }

    public function setStudentAppreciation(?Student $student_appreciation): self
    {
        $this->student_appreciation = $student_appreciation;

        return $this;
    }

    public function __toString()
    {
        return  $this->subject_name;
    }
}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Gender;
use App\Entity\SchoolClass;
use App\Entity\Student;
use Doctrine\ORM\EntityManager;
use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $builder
            ->add('first_name', TextType::class)
            ->add('last_name', TextType::class)
            ->add('schoolClass', EntityType::class, [
                'class' => SchoolClass::class,
                'choice_label' => 'level',
            ])
            ->add('gender', EntityType::class, [
                'class' => Gender::class,
                'choice_label' => 'gender_value',
            ]);
    }


    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Form\StudentType;
use App\Repository\GradeRepository;
use App\Repository\StudentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class StudentController extends AbstractController
{
    // Ajout d'un etudiant en bdd
    #[Route('/students/add', name: 'student_form')]
    public function form(Request $request, EntityManagerInterface $entityManager, int $id = null, StudentRepository $studentRepository): Response
    {

        $entity = $id ? $studentRepository->find($id) : new Student();
        $type = StudentType::class;

        $form = $this->createForm($type, $entity);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($entity);
            $entityManager->flush();

            return $this->redirectToRoute('student_form');
        }

        return $this->render('student/add_student.html.twig', [
            'form' => $form

        ]);
    }

    // affiche la liste des etudiants
    #[Route('/students', name: 'student_list')]
    public function index(StudentRepository $studentRepository): Response
    {
        $student = $studentRepository->findAll();

        //var_dump($student);

        return $this->render('student/students_list.html.twig', [
            'student' => $student,
        ]);
    }

    // affiche les details d'une note d'un etudiant
    #[Route('/grade/{id}', name: 'grade_details')]
    public function grades_details(int $id, GradeRepository $gradeRepository): Response
    {
        $studentInfos = $gradeRepository->find($id);

        //var_dump($studentInfos);

        return $this->render('student/grade_details.html.twig', [
            'studentInfos' => $studentInfos,
        ]);
    }


    // Afficher toutes les note d'un etudiant
    #[Route('/student/{id}', name: 'student_grades')]
    public function grade_list(int $id, StudentRepository $studentRepository): Response
    {
        $studentInfos = $studentRepository->find($id);

        //var_dump($studentInfos);

        return $this->render('student/grade_list.html.twig', [
            'studentInfos' => $studentInfos,
        ]);
    }
}

templates/student/add_student.html.twig
{% extends 'parent.html.twig' %}


{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('css/style.css')}}">
{% endblock %}
{% block body %}
{% block main %}


<h2 class="text-center">Formulaire</h2>

<form method="post">
<p>
{{ form_label(form.first_name, 'Prenom : ') }}
{{ form_widget(form.first_name, { attr : { placeholder: 'Prenom ', autofocus : 'autofocus'}}) }}
</p>
<p>
{{ form_label(form.last_name, 'Nom : ') }}
{{ form_widget(form.last_name, { attr : { placeholder: 'Nom'}}) }}
</p>
<p>
{{ form_label(form.gender, 'Genre : ') }}
{{ form_widget(form.gender) }}
</p>
<p>
{{ form_label(form.schoolClass, 'Classe : ') }}
{{ form_widget(form.schoolClass) }}
</p>

<p>
    <input type="submit" />
</p>

</form>


{% endblock%}
{% endblock %}

templates/student/grade_details.html.twig
{% extends 'parent.html.twig' %}

{% block title %}Hello TeacherController!{% endblock %}

{% block body %}
{% block main %}

<h2 class="text-center" >Note de {{ studentInfos.studentRating.lastName |capitalize}} {{ studentInfos.studentRating.firstName |capitalize}} </h2>
       <table class="table table-striped">
        <tr>
            <th>Matiere</th>
            <th>Note</th>
            
           
        </tr>
      
        <tr>
            <td>{{ studentInfos.subject.subjectName}}</td>
            
            <td> {{ studentInfos.value}} </td>
            
        
                     
        </tr>

        
    
     
           
</div>


{% endblock%}
{% endblock %}

templates/student/grade_list.html.twig
{% extends 'parent.html.twig' %}

{% block title %}Hello TeacherController!{% endblock %}

{% block body %}
{% block main %}

<h2 class="text-center" >Note de {{ studentInfos.lastName |capitalize}} {{ studentInfos.firstName |capitalize}} </h2>
       <table class="table table-striped">
            <tr>
                <th>Matiere</th>
                <th>Note</th>
                <th>Action</th>
                
            
            </tr>
            {% for grade in studentInfos.grade %}
            <tr>

                
                <td><a href="{{ path('grade_details', { 'id': grade.id }) }}">{{grade.subject.subjectName}}</td>
                <td><a href="{{ path('grade_details', { 'id': grade.id }) }}">{{ grade.value }} </a> </td>
                <td> 
                    <a href="{{ url('edit_grade', { id:grade.id}) }}" class="btn btn-info" >Modifier</a>
                    <a href="{{ url('delete_grade', { id:grade.id}) }}" class="btn btn-danger" >Supprimer</a>
                    
                </td>
               

                
            </tr>
            {% endfor %}
        

        
        </table>


        <table class="table table-striped">
            <tr>
                <th>Matiere</th>
                <th>Appreciation</th>
            
                
            
            </tr>
            {% for studentInfo in studentInfos.subjectAppreciation %}
            <tr>

                
                <td><a href="{{ url('edit_appreciation', { id:studentInfo.id}) }}" >{{studentInfo.subjectName}}</a></td>
                <td>{{studentInfo.appreciation}}</td>
               

                
            </tr>
            {% endfor %}

           
          
        
        
        </table>
       


{% endblock%}
{% endblock %}

templates/student/students_list.html.twig
{% extends 'parent.html.twig' %}

{% block title %}Hello TeacherController!{% endblock %}

{% block body %}
{% block main %}


       <table class="table table-striped">
        <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Genre</th>
            <th>Classe</th>
           
        </tr>
        {% for studentInfo in student %}
        <tr>
            
         
            <td><a href="{{ path('student_grades', { 'id': studentInfo.id }) }}">{{ studentInfo.lastName |capitalize}} </a></td>
            <td><a href="{{ path('student_grades', { 'id': studentInfo.id }) }}">{{ studentInfo.firstName |capitalize}} </a></td>
            <td>{{ studentInfo.gender |capitalize}}</td>
            <td>{{ studentInfo.schoolClass.level }}</td>
        
        
                     
        </tr>
     
        {% endfor %}            
</div>


{% endblock%}
{% endblock %}